/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config /tmp/wht-wrangler-types.jsonc --include-runtime false --strict-vars false` (hash: 74a12dc72725800c8a50433ebb0715e6)
interface __BaseEnv_Env {
	EVIDENCE: R2Bucket;
	DB: D1Database;
	DEEPSEEK_API_KEY: string;
	DEEPSEEK_MODEL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEEPSEEK_API_KEY" | "DEEPSEEK_MODEL">> {}
}
