/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false --strict-vars false` (hash: 626058692644a711896e38f5ef178fc4)
interface __BaseEnv_Env {
	DB: D1Database;
	DEEPSEEK_API_KEY: string;
	DEEPSEEK_MODEL: string;
	AI_PROVIDER: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEEPSEEK_API_KEY" | "DEEPSEEK_MODEL" | "AI_PROVIDER">> {}
}
