/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --config /tmp/wht-wrangler-types.jsonc --include-runtime false --strict-vars false` (hash: e9e35bb0ccb94bcf1ed5f35982723dfe)
interface __BaseEnv_Env {
	EVIDENCE: R2Bucket;
	DB: D1Database;
	OPENAI_API_KEY: string;
	OPENAI_MODEL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "OPENAI_MODEL">> {}
}
