import { type RecoveryCase } from "./types";

export const initialCases: RecoveryCase[] = [
  {
    id: "WHT-0241",
    customer: "Alpha Energy",
    invoice: "INV-1042",
    amount: 750000,
    stage: "in-dispute",
    exception: "TIN mismatch",
    age: 134,
    owner: "AO",
    confidence: 86,
    updated: "Today, 09:42",
    nextAction: "Request amended receipt and filing confirmation",
    narrative:
      "The invoice, payment gap and receipt amount agree. The beneficiary TIN on the receipt differs from the approved company master record.",
    evidence: [
      {
        label: "Invoice",
        reference: "INV-1042",
        detail: "NGN 15,000,000",
        state: "verified",
      },
      {
        label: "Payment",
        reference: "PAY-8827",
        detail: "NGN 14,250,000",
        state: "verified",
      },
      {
        label: "WHT receipt",
        reference: "RCP-22814",
        detail: "Wrong beneficiary TIN",
        state: "warning",
      },
      {
        label: "Authority record",
        reference: "Not found",
        detail: "Awaiting correction",
        state: "missing",
      },
    ],
    checks: [
      {
        label: "Customer",
        bookValue: "Alpha Energy Ltd",
        evidenceValue: "Alpha Energy Limited",
        result: "match",
      },
      {
        label: "Beneficiary TIN",
        bookValue: "01234567-0001",
        evidenceValue: "01234576-0001",
        result: "mismatch",
      },
      {
        label: "WHT amount",
        bookValue: "NGN 750,000",
        evidenceValue: "NGN 750,000",
        result: "match",
      },
      {
        label: "Reporting period",
        bookValue: "Mar 2026",
        evidenceValue: "Mar 2026",
        result: "match",
      },
    ],
  },
  {
    id: "WHT-0238",
    customer: "Metro Foods",
    invoice: "INV-1077",
    amount: 185000,
    stage: "evidence-needed",
    exception: "Receipt missing",
    age: 71,
    owner: "AA",
    confidence: 72,
    updated: "Yesterday, 16:18",
    nextAction: "Request deduction receipt from accounts payable",
    narrative:
      "The payment gap is consistent with the expected deduction, but no receipt or remittance advice is attached to the transaction.",
    evidence: [
      {
        label: "Invoice",
        reference: "INV-1077",
        detail: "NGN 3,700,000",
        state: "verified",
      },
      {
        label: "Payment",
        reference: "PAY-8792",
        detail: "NGN 3,515,000",
        state: "verified",
      },
      {
        label: "WHT receipt",
        reference: "Missing",
        detail: "Request required",
        state: "missing",
      },
      {
        label: "Authority record",
        reference: "Not checked",
        detail: "Blocked by missing evidence",
        state: "pending",
      },
    ],
    checks: [
      {
        label: "Customer",
        bookValue: "Metro Foods Plc",
        evidenceValue: "Metro Foods Plc",
        result: "match",
      },
      {
        label: "Payment gap",
        bookValue: "NGN 185,000",
        evidenceValue: "NGN 185,000",
        result: "match",
      },
      {
        label: "WHT receipt",
        bookValue: "Expected",
        evidenceValue: "Not provided",
        result: "missing",
      },
      {
        label: "Reporting period",
        bookValue: "Apr 2026",
        evidenceValue: "Unknown",
        result: "missing",
      },
    ],
  },
  {
    id: "WHT-0234",
    customer: "Civic Works",
    invoice: "INV-1099",
    amount: 420000,
    stage: "recognised",
    exception: "No open exception",
    age: 18,
    owner: "AO",
    confidence: 100,
    updated: "29 Jul, 11:05",
    nextAction: "Confirm utilisation against the next eligible liability",
    narrative:
      "The invoice, payment, receipt and authority record agree. The credit is recognised and ready for utilisation review.",
    evidence: [
      {
        label: "Invoice",
        reference: "INV-1099",
        detail: "NGN 8,400,000",
        state: "verified",
      },
      {
        label: "Payment",
        reference: "PAY-8739",
        detail: "NGN 7,980,000",
        state: "verified",
      },
      {
        label: "WHT receipt",
        reference: "RCP-22409",
        detail: "All required fields present",
        state: "verified",
      },
      {
        label: "Authority record",
        reference: "CR-90218",
        detail: "Credit recognised",
        state: "verified",
      },
    ],
    checks: [
      {
        label: "Customer",
        bookValue: "Civic Works Ltd",
        evidenceValue: "Civic Works Ltd",
        result: "match",
      },
      {
        label: "Beneficiary TIN",
        bookValue: "08173492-0001",
        evidenceValue: "08173492-0001",
        result: "match",
      },
      {
        label: "WHT amount",
        bookValue: "NGN 420,000",
        evidenceValue: "NGN 420,000",
        result: "match",
      },
      {
        label: "Reporting period",
        bookValue: "May 2026",
        evidenceValue: "May 2026",
        result: "match",
      },
    ],
  },
  {
    id: "WHT-0229",
    customer: "Northstar Ltd",
    invoice: "INV-1113",
    amount: 90000,
    stage: "matched",
    exception: "Amount differs",
    age: 42,
    owner: "TM",
    confidence: 64,
    updated: "28 Jul, 14:32",
    nextAction: "Review the VAT and WHT calculation basis",
    narrative:
      "The documents refer to the same transaction, but the receipt amount is NGN 7,500 below the payment-gap candidate.",
    evidence: [
      {
        label: "Invoice",
        reference: "INV-1113",
        detail: "NGN 1,800,000",
        state: "verified",
      },
      {
        label: "Payment",
        reference: "PAY-8690",
        detail: "NGN 1,710,000",
        state: "verified",
      },
      {
        label: "WHT receipt",
        reference: "RCP-22097",
        detail: "NGN 82,500",
        state: "warning",
      },
      {
        label: "Authority record",
        reference: "CR-89871",
        detail: "NGN 82,500",
        state: "warning",
      },
    ],
    checks: [
      {
        label: "Customer",
        bookValue: "Northstar Ltd",
        evidenceValue: "Northstar Limited",
        result: "match",
      },
      {
        label: "Beneficiary TIN",
        bookValue: "02941763-0001",
        evidenceValue: "02941763-0001",
        result: "match",
      },
      {
        label: "WHT amount",
        bookValue: "NGN 90,000",
        evidenceValue: "NGN 82,500",
        result: "mismatch",
      },
      {
        label: "Reporting period",
        bookValue: "May 2026",
        evidenceValue: "May 2026",
        result: "match",
      },
    ],
  },
  {
    id: "WHT-0225",
    customer: "Horizon Logistics",
    invoice: "INV-1120",
    amount: 310000,
    stage: "detected",
    exception: "Unexplained short payment",
    age: 9,
    owner: "Unassigned",
    confidence: 58,
    updated: "27 Jul, 08:16",
    nextAction: "Confirm transaction classification and deduction basis",
    narrative:
      "A material payment gap was detected. The system needs reviewer confirmation before treating it as a WHT receivable.",
    evidence: [
      {
        label: "Invoice",
        reference: "INV-1120",
        detail: "NGN 6,200,000",
        state: "verified",
      },
      {
        label: "Payment",
        reference: "PAY-8644",
        detail: "NGN 5,890,000",
        state: "verified",
      },
      {
        label: "WHT receipt",
        reference: "Not assessed",
        detail: "Classification pending",
        state: "pending",
      },
      {
        label: "Authority record",
        reference: "Not assessed",
        detail: "Classification pending",
        state: "pending",
      },
    ],
    checks: [
      {
        label: "Customer",
        bookValue: "Horizon Logistics",
        evidenceValue: "Horizon Logistics",
        result: "match",
      },
      {
        label: "Payment gap",
        bookValue: "NGN 310,000",
        evidenceValue: "NGN 310,000",
        result: "match",
      },
      {
        label: "WHT applicability",
        bookValue: "Unconfirmed",
        evidenceValue: "No receipt",
        result: "missing",
      },
      {
        label: "Reporting period",
        bookValue: "Jun 2026",
        evidenceValue: "Unknown",
        result: "missing",
      },
    ],
  },
  {
    id: "WHT-0217",
    customer: "Delta Projects",
    invoice: "INV-1018",
    amount: 265000,
    stage: "closed",
    exception: "Utilised",
    age: 0,
    owner: "TM",
    confidence: 100,
    updated: "22 Jul, 10:01",
    nextAction: "No further action",
    narrative:
      "The recognised credit was applied and the case was closed with complete supporting evidence.",
    evidence: [
      {
        label: "Invoice",
        reference: "INV-1018",
        detail: "Verified",
        state: "verified",
      },
      {
        label: "Payment",
        reference: "PAY-8421",
        detail: "Verified",
        state: "verified",
      },
      {
        label: "WHT receipt",
        reference: "RCP-21612",
        detail: "Verified",
        state: "verified",
      },
      {
        label: "Authority record",
        reference: "CR-88107",
        detail: "Utilised",
        state: "verified",
      },
    ],
    checks: [
      {
        label: "Customer",
        bookValue: "Delta Projects Ltd",
        evidenceValue: "Delta Projects Ltd",
        result: "match",
      },
      {
        label: "Beneficiary TIN",
        bookValue: "04491827-0001",
        evidenceValue: "04491827-0001",
        result: "match",
      },
      {
        label: "WHT amount",
        bookValue: "NGN 265,000",
        evidenceValue: "NGN 265,000",
        result: "match",
      },
      {
        label: "Utilisation",
        bookValue: "Expected",
        evidenceValue: "Confirmed",
        result: "match",
      },
    ],
  },
];

export const initialImportBatches = [
  {
    name: "July WHT ledger.csv",
    rows: 184,
    status: "Validated",
    time: "Today, 08:32",
  },
  {
    name: "Receipt bundle 07.pdf",
    rows: 27,
    status: "Reviewed",
    time: "Yesterday, 15:11",
  },
];
